### ISSUE TITLE
add git tags for pypi versions

### ISSUE THREAD

**Issue by milahu** [sysr-q/flask-themes2#13]
https://pypi.org/project/Flask-Themes2/#history

**Comment by sysr-q** [comment]
Hello. Sorry for the delays, corpo world has had me busy.

I've gone back and tagged the PyPi releases and pushed them to GitHub. It looks like 0.1.2 was just from some code changes I made but never committed (naughty naughty 2013 Chris). It jumped right from 0.1.1 to 0.1.3 (mislabeled 0.13 in the code) with the 0.1.2 changes mixed by hand it seems.

Let me know if you need anything else! 😸
